// Generated by scripts/build-pwa.mjs from data/trip-manifest.json. Do not hand-edit.
function deepFreeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
  }
  return value;
}
export const companionData = deepFreeze({
  "identity": {
    "companionVersion": "0.6.0-candidate.12",
    "releaseStatus": "candidate",
    "dataVersion": "1.0.0",
    "sourceRelease": "v15.3.10",
    "sourceCommit": "fb711292b2642c2296eb76c0cfe2531606029609",
    "generatedAt": "2026-08-11T13:37:49Z",
    "verifiedAt": "2026-08-07T07:45:17Z",
    "manifestSha256": "3cda95d4e6b1d5d7138dd2ca3320501d9b59076a0f9c9cfb3e67117ed5384758",
    "manifestShort": "3cda95d4e6b1",
    "bundleId": "ddmg-companion-0-6-0-candidate-12-data-3cda95d4e6b1-b1",
    "offlineBundleVersion": 1,
    "publicBaseUrl": "https://companion.vondadowns.com/"
  },
  "trip": {
    "name": "Lake Como / Blanca / Ellingwood / Mount Lindsey 2026",
    "area": "Lake Como, Blanca Peak, Ellingwood Point, and Mount Lindsey",
    "startDate": "2026-08-19",
    "endDate": "2026-08-25",
    "primaryClimbDate": "2026-08-23",
    "timezone": "America/Denver"
  },
  "objectives": [
    {
      "id": "objective-lake-como-approach",
      "name": "Lake Como approach and camp",
      "role": "approach",
      "objectiveType": "camp_approach",
      "plannedDate": "2026-08-22",
      "planningTimes": [
        {
          "id": "planning-lake-como-start",
          "kind": "planned_start",
          "localTime": "10:00",
          "timezone": "America/Denver",
          "label": "Lake Como approach planned start",
          "semantics": "planned_start",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "Road clearance, conditions, and driver judgment determine the actual starting point and time."
        },
        {
          "id": "planning-lake-como-camp-target",
          "kind": "turnaround_or_exit_target",
          "localTime": "15:30",
          "timezone": "America/Denver",
          "label": "Lake Como reach-camp planning target",
          "semantics": "user_defined_planning_target",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "This target preserves recovery margin; it does not determine whether travel is permitted."
        }
      ]
    },
    {
      "id": "objective-blanca-ellingwood-combination",
      "name": "Blanca Peak + Ellingwood Point",
      "role": "primary",
      "objectiveType": "route_combination",
      "plannedDate": "2026-08-23",
      "planningTimes": [
        {
          "id": "planning-blanca-ellingwood-start",
          "kind": "planned_start",
          "localTime": "04:15",
          "timezone": "America/Denver",
          "label": "Blanca and Ellingwood planned start",
          "semantics": "planned_start",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "The planned start remains fixed unless the owner creates a new canonical data version."
        },
        {
          "id": "planning-blanca-ellingwood-exit-target",
          "kind": "turnaround_or_exit_target",
          "localTime": "11:30",
          "timezone": "America/Denver",
          "label": "Below-exposed-terrain planning target",
          "semantics": "user_defined_planning_target",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "This is a user-defined planning target, not a calculated safety cutoff, weather permission, or continuation threshold."
        }
      ]
    },
    {
      "id": "objective-mount-lindsey",
      "name": "Mount Lindsey",
      "role": "separate_planned",
      "objectiveType": "summit",
      "plannedDate": "2026-08-24",
      "planningTimes": [
        {
          "id": "planning-mount-lindsey-start",
          "kind": "planned_start",
          "localTime": "05:15",
          "timezone": "America/Denver",
          "label": "Mount Lindsey planned start",
          "semantics": "planned_start",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "Current access, route conditions, and group judgment govern the actual climb."
        },
        {
          "id": "planning-mount-lindsey-return-target",
          "kind": "turnaround_or_exit_target",
          "localTime": "12:00",
          "timezone": "America/Denver",
          "label": "Mount Lindsey return/exit planning target",
          "semantics": "user_defined_planning_target",
          "userDefined": true,
          "automaticCalculation": false,
          "authorizationEffect": "none",
          "safetyNote": "This is a planning target; access, weather, terrain, pace, and group condition govern reassessment."
        }
      ]
    }
  ],
  "decisions": [
    {
      "id": "decision-forecast-versus-actual",
      "objectiveIds": [
        "objective-lake-como-approach",
        "objective-blanca-ellingwood-combination",
        "objective-mount-lindsey"
      ],
      "dimension": "weather_evidence",
      "prompt": "Compare the saved forecast timestamp with actual sky, wind, and cloud growth at departure."
    },
    {
      "id": "decision-upper-basin-reassessment",
      "objectiveIds": [
        "objective-blanca-ellingwood-combination"
      ],
      "dimension": "pace_group_weather",
      "prompt": "At the upper basin, reassess wind, cloud growth, pace, comfort, and group condition."
    },
    {
      "id": "decision-blanca-ellingwood-traverse",
      "objectiveIds": [
        "objective-blanca-ellingwood-combination"
      ],
      "dimension": "route_exposure",
      "prompt": "Before the Blanca–Ellingwood traverse, reassess weather, rock, time, and every climber's comfort; the traverse remains optional."
    },
    {
      "id": "decision-turn-or-descend",
      "objectiveIds": [
        "objective-blanca-ellingwood-combination"
      ],
      "dimension": "turnaround_descent",
      "prompt": "Turn or descend for thunder or rapidly building convection, balance-impairing wind, worsening altitude symptoms, unacceptable rockfall or route conditions, any climber declining the Class 3 traverse, or exposure after the agreed planning target."
    },
    {
      "id": "decision-mount-lindsey-access",
      "objectiveIds": [
        "objective-mount-lindsey"
      ],
      "dimension": "access",
      "prompt": "Before leaving service, confirm current Mount Lindsey access and waiver requirements; route conditions and group judgment govern."
    }
  ],
  "routes": [
    {
      "id": "route-lake-como-approach-8000",
      "objectiveId": "objective-lake-como-approach",
      "objectiveRole": "approach",
      "name": "Lake Como Approach from near 8,000 ft",
      "distanceScope": "round_trip",
      "distanceScopeLabel": "round trip",
      "distanceMiles": 11.25,
      "elevationGainFt": 3900,
      "difficulty": "Class 1",
      "exposure": "Low",
      "notes": "Published approach profile. Current route-reference evidence explicitly labels 11.25 miles as round-trip. The 3,900 ft figure is retained as upstream cumulative gain and is not replaced by endpoint subtraction.",
      "returnConsiderations": "Road clearance determines the actual starting point; do not force the vehicle higher than conditions support."
    },
    {
      "id": "route-lake-como-approach-8800",
      "objectiveId": "objective-lake-como-approach",
      "objectiveRole": "approach",
      "name": "Lake Como Approach from near 8,800 ft",
      "distanceScope": "round_trip",
      "distanceScopeLabel": "round trip",
      "distanceMiles": 8.5,
      "elevationGainFt": 3100,
      "difficulty": "Class 1",
      "exposure": "Low",
      "notes": "Published approach profile. Current route-reference evidence explicitly labels 8.5 miles as round-trip. The 3,100 ft figure is retained as upstream cumulative gain and is not replaced by endpoint subtraction.",
      "returnConsiderations": "Road clearance determines the actual starting point; do not force the vehicle higher than conditions support."
    },
    {
      "id": "route-blanca-ellingwood-combination",
      "objectiveId": "objective-blanca-ellingwood-combination",
      "objectiveRole": "primary",
      "name": "Combo: Blanca + Ellingwood from Lake Como camp",
      "distanceScope": "round_trip",
      "distanceScopeLabel": "round trip",
      "distanceMiles": 7,
      "elevationGainFt": 3000,
      "difficulty": "Class 3",
      "exposure": "Considerable",
      "notes": "The connecting ridge has a Class 3 line or a return to the standard trail before reascending; choosing the Class 3 line is a separate decision from choosing the combination.",
      "returnConsiderations": "The traverse remains optional. Weather, rock, time, and every climber's comfort decide the sequence."
    },
    {
      "id": "route-mount-lindsey-standard",
      "objectiveId": "objective-mount-lindsey",
      "objectiveRole": "separate_planned",
      "name": "Mount Lindsey — Northwest Gully",
      "distanceScope": "round_trip",
      "distanceScopeLabel": "round trip",
      "distanceMiles": 8.25,
      "elevationGainFt": 3500,
      "difficulty": "Easy Class 3",
      "exposure": "Considerable",
      "notes": "Frozen source states that a waiver is required and legal access is from Lily Lake Trailhead via the standard gully or ridge route.",
      "returnConsiderations": "The frozen source does not store the trailhead elevation, so no net descent figure is inserted."
    }
  ],
  "lilyLake": {
    "name": "Lily Lake Trailhead",
    "latitude": null,
    "longitude": null,
    "elevationFt": null,
    "verificationStatus": "pending_external_verification"
  },
  "contacts": [
    {
      "id": "contact-alamosa-county",
      "agency": "Alamosa County Sheriff’s Office",
      "role": "Contextual county dispatch and sheriff reference",
      "geographicContext": "Lake Como and the Alamosa-side approach may involve Alamosa County; summit-area incidents may involve Costilla County.",
      "activationNotes": "Call 911 first. Dispatch determines the responding agency from the exact incident location.",
      "externallyVerifiedAt": "2026-08-07T07:45:17Z",
      "phones": [
        {
          "kind": "dispatch",
          "label": "County dispatch",
          "display": "719-589-5807",
          "tel": "tel:+17195895807"
        },
        {
          "kind": "office",
          "label": "Sheriff’s office",
          "display": "719-589-6608",
          "tel": "tel:+17195896608"
        }
      ]
    },
    {
      "id": "contact-huerfano-county",
      "agency": "Huerfano County Sheriff’s Office",
      "role": "Contextual county dispatch and sheriff reference",
      "geographicContext": "Lily Lake and trailhead-side incidents may involve Huerfano County; summit-area incidents may involve Costilla County.",
      "activationNotes": "Call 911 first. Dispatch determines the responding agency from the exact incident location.",
      "externallyVerifiedAt": "2026-08-07T07:45:17Z",
      "phones": [
        {
          "kind": "dispatch",
          "label": "County dispatch",
          "display": "719-738-1044",
          "tel": "tel:+17197381044"
        },
        {
          "kind": "office",
          "label": "Sheriff’s office",
          "display": "719-738-1600",
          "tel": "tel:+17197381600"
        }
      ]
    },
    {
      "id": "contact-costilla-county",
      "agency": "Costilla County Sheriff’s Office",
      "role": "Contextual summit-area dispatch and sheriff reference",
      "geographicContext": "Summit-area incidents on Blanca Peak, Ellingwood Point, or Mount Lindsey may involve Costilla County; exact incident location controls.",
      "activationNotes": "Call 911 first. Dispatch determines the responding agency from the exact incident location.",
      "externallyVerifiedAt": "2026-08-07T07:45:17Z",
      "phones": [
        {
          "kind": "dispatch",
          "label": "County dispatch",
          "display": "719-672-3302",
          "tel": "tel:+17196723302"
        },
        {
          "kind": "office",
          "label": "Sheriff’s office",
          "display": "719-672-0673",
          "tel": "tel:+17196720673"
        }
      ]
    }
  ],
  "communication": {
    "milestones": [
      "Vehicle departure",
      "Lake Como camp",
      "Summit start",
      "Summit or high point",
      "Below exposed terrain",
      "Back at camp",
      "Back at vehicle",
      "Fort Garland",
      "Home"
    ],
    "emergencySequence": [
      "Call 911 first.",
      "Provide exact location, mountain, route, elevation, and coordinates if available.",
      "Provide injuries, party size, weather, and current conditions.",
      "Let dispatch determine the responding agency."
    ]
  },
  "invariants": {
    "weather": "Weather is evidence, not permission.",
    "emergency": "Call 911 first.",
    "jurisdiction": "Dispatch determines the responding agency from the exact incident location.",
    "planning": "A user-defined planning target is not automatic route authorization.",
    "conditions": "Actual conditions govern the decision."
  },
  "weatherSnapshot": {
    "available": true,
    "summary": "Packaged alpine reference points for Lake Como area, Blanca Peak, Ellingwood Point, and Mount Lindsey. Reassess actual sky, wind, and cloud buildup against packaged planning context.",
    "source": "Mountain Guide v15.3.10 (fb711292b264) · Verified 2026-08-07",
    "timestamp": "2026-08-07T07:45:17Z",
    "statement": "Weather is evidence, not permission.",
    "locations": [
      {
        "id": "weather-lake-como-area",
        "name": "Lake Como area",
        "elevationFt": 11750,
        "context": "Saturday approach reference point; no forecast values are canonical."
      },
      {
        "id": "weather-blanca-peak",
        "name": "Blanca Peak",
        "elevationFt": 14350,
        "context": "Sunday summit reference point; no forecast values are canonical."
      },
      {
        "id": "weather-ellingwood-point",
        "name": "Ellingwood Point",
        "elevationFt": 14057,
        "context": "Sunday summit reference point; no forecast values are canonical."
      },
      {
        "id": "weather-mount-lindsey",
        "name": "Mount Lindsey",
        "elevationFt": 14055,
        "context": "Monday summit reference point; no forecast values are canonical."
      },
      {
        "id": "weather-great-sand-dunes",
        "name": "Great Sand Dunes",
        "elevationFt": 8200,
        "context": "Friday visit reference point; it is not a climbing objective and no forecast values are canonical."
      }
    ]
  },
  "artifacts": {
    "fieldGuide": {
      "url": "./generated/field-guide.pdf",
      "sha256": "3ac4b8b512637d99d44263ae5ab97d75650a06bf75b0b65797cd585329517523",
      "pages": [
        {
          "page": 1,
          "path": "generated/field-guide-p1.png",
          "sha256": "0f918ff956e2b35813912c7dddb68496052065f44e2c7076259c016ac650a27b"
        },
        {
          "page": 2,
          "path": "generated/field-guide-p2.png",
          "sha256": "00f3593ed712f23f14578cc5e6e4e2f5be0b909d0d2f5f2d9de345f6a096a726"
        },
        {
          "page": 3,
          "path": "generated/field-guide-p3.png",
          "sha256": "ec786cbcdef2bc6ef5038744589363fadae6ecef7b0b7168fd4d610893c05140"
        }
      ]
    },
    "pocketCard": {
      "url": "./generated/pocket-card.pdf",
      "sha256": "99fbd6b99b3ccaa641bbfc7f5d68244728e22985c373c44db870088b74226958",
      "pages": [
        {
          "page": 1,
          "side": "front",
          "path": "generated/pocket-card-p1.png",
          "sha256": "a36a1f6810af511b480aba370ffeb9211d1c990a5c1aaa8d5edfedb2cd552b08"
        },
        {
          "page": 2,
          "side": "back",
          "path": "generated/pocket-card-p2.png",
          "sha256": "86d148c45db91a2b50e31304766edc2e81da87cc4b8c440f59a264de5ad97645"
        }
      ]
    }
  }
});
export const releaseMetadata = deepFreeze({
  "companion_version": "0.6.0-candidate.12",
  "data_version": "1.0.0",
  "manifest_sha256": "3cda95d4e6b1d5d7138dd2ca3320501d9b59076a0f9c9cfb3e67117ed5384758",
  "source_release": "v15.3.10",
  "source_commit": "fb711292b2642c2296eb76c0cfe2531606029609",
  "generated_at": "2026-08-11T13:37:49Z",
  "verified_at": "2026-08-07T07:45:17Z",
  "release_status": "candidate",
  "bundle_id": "ddmg-companion-0-6-0-candidate-12-data-3cda95d4e6b1-b1",
  "offline_bundle_version": 1,
  "offline_bundle_url": "https://companion.vondadowns.com/offline-bundle.json",
  "pwa_url": "https://companion.vondadowns.com/",
  "field_guide_url": "https://companion.vondadowns.com/generated/field-guide.pdf",
  "pocket_card_url": "https://companion.vondadowns.com/generated/pocket-card.pdf"
});
